# Generated by Django 5.1.7 on 2025-03-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Ramais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ramal', models.IntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('email', models.CharField(default='example@example.com', max_length=100)),
                ('ip', models.CharField(default='192.168.254.0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ramal', models.IntegerField()),
                ('email', models.CharField(default='example@gmr.com.br', max_length=100)),
                ('departamentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramais.departamento')),
            ],
        ),
    ]
